HPV = 'handled_platver'
UHPV = 'unhandled_platver'
NAVI = 'navi'
FILELINE = 'fileline'
EXTRA = 'extra'

STARTLINE = 'startline'
PLATVER = 'platver'
USERID = 'userid'
USERIP = 'userip'
SUPPORT = 'support'

REQ = 'req'
REP = 'rep'
SUCCESS = 'success'
FAILED = 'failed'
ERRCODE = 'errcode'

# network states.
NET_UNKNOWN = 'unknown'
NET_NONE = 'none'
NET_WIFI = 'wifi'
NET_4G = '4g'
NET_3G = '3g'
NET_2G = '2g'